service: proyecto-demo
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12

# provider:
#   name: aws
#   runtime: nodejs18.x


functions:
  demoSNS:
    handler: handler.process_sns  # Nombre del archivo y la función Lambda
    events:
      - sns: 
          arn: "arn:aws:sns:us-east-1:123456789012:test-topic"

custom:
  serverless-offline-sns:
    localPort: 4002
    remotePort: 3002
    #sns-endpoint: http://localhost:4002
    debug: true

plugins:
  - serverless-offline-sns
  - serverless-offline
  #- serverless-dynamodb-local
#  - serverless-python-requirements  # Plugin para gestionar dependencias si las usas